DROP TABLE STUDENT;
CREATE TABLE STUDENT (
    STUD_NUMBER         NUMBER(5) CONSTRAINT STUDENT_NUM_PK PRIMARY KEY,
    STUD_LNAME          VARCHAR2(30) NOT NULL,
    STUD_FNAME          VARCHAR2(30) NOT NULL,
    STUD_SALUTATION     VARCHAR2(5), CONSTRAINT STUD_SAL_C CHECK(STUD_SALUTATION IN ('Mr.', 'Ms.', 'Miss', 'Hon.', 'Rev', 'Prof.', 'Dr.')),
    STUD_GENDER         CHAR(1) NOT NULL,
    STUD_ADDRESS        VARCHAR(100),
    STUD_POSTAL_CODE    CHAR(3), CONSTRAINT STUD_PC_FK FOREIGN KEY (STUD_POSTAL_CODE) REFERENCES ADDRESS (POSTAL_CODE),
    STUD_DOB_YEAR       NUMBER(4), CONSTRAINT STUD_DOB_C CHECK (STUD_DOB_YEAR > 1950),
    HALL_NUMBER         VARCHAR(5) NOT NULL,CONSTRAINT HALL_NUM_FK FOREIGN KEY (HALL_NUMBER) REFERENCES HALL (HALL_NUMBER),
    PROG_NUMBER         CHAR(5)NOT NULL, CONSTRAINT PROG_NUM_FK FOREIGN KEY (PROG_NUMBER) REFERENCES PROGRAM (PROG_NUMBER)
);

DROP TABLE PROGRAM;
CREATE TABLE PROGRAM (
    PROG_NUMBER     CHAR(5) CONSTRAINT PROG_NUM_PK PRIMARY KEY,
    PROG_NAME       VARCHAR2(100) NOT NULL,  CONSTRAINT PROG_NAME_U UNIQUE(PROG_NAME)
);

DROP TABLE HALL;
CREATE TABLE HALL (
    HALL_NUMBER     VARCHAR2(5) CONSTRAINT HALL_NUM_PK PRIMARY KEY,
    HALL_NAME       VARCHAR2(100) NOT NULL, CONSTRAINT HALL_NAME_U UNIQUE(HALL_NAME)
);

DROP TABLE DEPARTMENT;
CREATE TABLE DEPARTMENT (
    DEPT_NUMBER     CHAR(3) CONSTRAINT DEPT_NUM_PK PRIMARY KEY,
    DEPT_NAME       VARCHAR2(100) NOT NULL,
    DEPT_HEAD       CHAR(3) NOT NULL, CONSTRAINT DEPT_HEAD_FK FOREIGN KEY (DEPT_HEAD) REFERENCES STAFF (STAFF_NUMBER),
    DEPT_DIV_NUMBER CHAR(3) NOT NULL, CONSTRAINT DEPT_DIV_NUMBER FOREIGN KEY (DEPT_DIV_NUMBER) REFERENCES DIVISION (DIV_NUMBER)
);

DROP TABLE STAFF;
CREATE TABLE STAFF (
    STAFF_NUMBER        CHAR(3) CONSTRAINT STAFF_NUM_PK PRIMARY KEY, CONSTRAINT STAFF_NUMBER_C CHECK(INSTR(STAFF_NUMBER, 'S') = 1),
    STAFF_SALUTATION    VARCHAR2(5), CONSTRAINT STAFF_SAL_C CHECK(STAFF_SALUTATION IN ('Mr.', 'Ms', 'Miss', 'Hon.', 'Rev', 'Prof.', 'Dr.')),
    STAFF_LNAME         VARCHAR2(30) NOT NULL, 
    STAFF_FNAME         VARCHAR2(30) NOT NULL
);

DROP TABLE COURSE;
CREATE TABLE COURSE (
    CRS_CODE    CHAR(5) CONSTRAINT CRS_CODE_PK PRIMARY KEY,
    CRS_NAME    VARCHAR2(50) NOT NULL, CONSTRAINT CRS_NAME_U UNIQUE(CRS_NAME)
);

DROP TABLE DIVISION;
CREATE TABLE DIVISION (
    DIV_NUMBER      CHAR(3) CONSTRAINT DIV_NUMBER_PK PRIMARY KEY,
    DIV_NAME        VARCHAR2(50) NOT NULL, CONSTRAINT DIV_NAME_U UNIQUE(DIV_NAME),
    DIV_HEAD        CHAR(3)DEFAULT NULL 
);

DROP TABLE PROGRAM_STRUCTURE;
CREATE TABLE PROGRAM_STRUCTURE (
    PROG_NUMBER          CHAR(5),
    COURSE_CODE          CHAR(5),
    COURSE_SEQ_NUMBER    NUMBER(3) DEFAULT 1 NOT NULL,
    CONSTRAINT PROGRAM_STRUCTURE_PK PRIMARY KEY (PROG_NUMBER, COURSE_CODE),
    CONSTRAINT PS_CODE_FK FOREIGN KEY (COURSE_CODE) REFERENCES COURSE(CRS_CODE),
    CONSTRAINT PS_PROGNUM_FK FOREIGN KEY (PROG_NUMBER) REFERENCES PROGRAM(PROG_NUMBER)
);
    
DROP TABLE ADDRESS;
CREATE TABLE ADDRESS (
    POSTAL_CODE     CHAR(3) CONSTRAINT POSTAL_CODE_PK PRIMARY KEY, CONSTRAINT POSTAL_CODE_C CHECK(LENGTH(POSTAL_CODE) >= 3), 
    PLACE_NAME      VARCHAR2(200) DEFAULT NULL,
    PROVINCE        VARCHAR(30) DEFAULT NULL
);


    
    